spring:
  application:
    name: currencycapi
  datasource:
    url: jdbc:mysql://148.135.93.196:3306/currency
    username: currency
    password: NpR3PmeSAcfxFx2T
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8001

eureka:
  instance:
    hostname: currencycapi
    appname: currencycapi
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
