spring:
  application:
    name: currencycrond
  datasource:
    url: jdbc:mysql://148.135.93.196:3306/currency
    username: currency
    password: NpR3PmeSAcfxFx2T
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 148.135.93.196
    port: 6379
    password: s9636h8n2455
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间

server:
  port: 8003

eureka:
  instance:
    hostname: currencycrond
    appname: currencycrond
  client:
    serviceUrl:
      defaultZone: http://148.135.93.196:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.minyan.po

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

thread:
  pool:
    executor:
      config:
        corePoolSize: 20
        maxPoolSize: 50
        keepAliveTime: 5000
        blockQueueSize: 5000
        policy: CallerRunsPolicy